#ifndef __DIANRU_OBCODE_H__
#define __DIANRU_OBCODE_H__
#define getDianruDeviceOrientation getRunToolBar
#define setDianruRequestLaseTimeWithUrl setFowardWebView
#define dianruViewload ReadWebView
#define dianruStartEGOUpdate CreateSegment
#define dianruSpendScoreResultCallback QueryView
#define getDianruMainBounds getCompareWebView
#define dianruObjectForKey BuildWindow
#define dianruDidJumpedView IndexTableViewCell
#define YQL_V CollectTable
#define getDianruAppId getCreateTable
#define dianruFindview ReadPicker
#define YQLHttpActionExecer ReplaceCell
#define dianruWithMySelf WaitCell
#define YQLAlignCenter CompileCell
#define YQLANIMATION_TYPE ReadActivityView
#define dianruQueryString ApendProgress
#define dianruResizeToFit NextToolBar
#define dianruAddRefreshView PrintSlider
#define YQLMacros MatchTableCell
#define dianruEnable ParseSwitch
#define dianruRequestBlock HoldTable
#define dianruImageFor ParseView
#define dianruTimeout BuildCell
#define YQLTextureInfo ReplaceActivityView
#define dianruExpire PutNavigationBar
#define YQLViewUnknow StartWithToolBar
#define dianruParseEvent PrintSegment
#define dianruParseFloat AddTableCell
#define dianruDidReportedView PutImage
#define YQLTextureVertical CreateTableCell
#define YQLReqestResultType NextWebView
#define YQLViewCell ApendSwitch
#define getDianruSpendScore getHashWindow
#define YQLTextureHorizontal GetCell
#define dianruShareIstance HoldWindow
#define dianruActions FunctionSegment
#define dianruBuildWithName FunctionActivityView
#define setDianruNode setFindTabBar
#define dianruDuration DoAlertView
#define YQLNotificationAction ApendPicker
#define dianruExec IteratorAlertView
#define dianruLoadView HashTable
#define dianruApplicationKey IteratorActivityView
#define addDianruStyle ReplaceWebView
#define dianruRequestSpace FunctionWindow
#define dianruCreate FindToolBar
#define dianruContext BuildWebView
#define dianruCancel CompareTableCell
#define YQLAlignLeft NewNavigationBar
#define YQLViewText FindView
#define initWithDianruContext initSetCell
#define dianruName GetTableCell
#define dianruParseTextAttr SleepTableViewCell
#define getDianruMacAddress getCollectTableCell
#define setDianruArrowData setHoldButton
#define YQLHttpRequest FunctionSwitch
#define dianruSubview BuildToolBar
#define setDianruDelegateNull setGetNavigationBar
#define dianruReadNetDataTaskFor RunWebView
#define dianruStopLoadAnimation CompilePicker
#define dianruFsPath WaitToolBar
#define dianruEnableUseRadius HoldActivityView
#define dianruDidDataReceivedView ApendTableViewCell
#define YQLActionNode CompileNavigationBar
#define dianruWakeup NewPicker
#define YQLFontBold PrintActivityView
#define YQLViewSection ParseNavigationBar
#define YQLUrlCache FunctionProgress
#define dianruMovieFinishedCallback RunTableViewCell
#define YQLViewSimple ParseSegment
#define dianruLoadData DoPicker
#define dianruHide FindSwitch
#define dianruResult waitTableCell
#define dianruRemove FowardTableViewCell
#define YQLFontStyle_ALL GetWindow
#define YQLViewDelegate EndWithView
#define refreshDianruTableHeaderDidTriggerRefresh CompareTableViewCell
#define dianruRect HoldView
#define dianruStartRotation SleepWebView
#define YQLViewTable ReadTableViewCell
#define addDianruChild RunView
#define dianruPurge PutView
#define YQLHttpAction ReplaceNavigationBar
#define YQLOPullRefreshLoading SetNavigationBar
#define dianruText PrintTable
#define dianruImage BuildNavigationBar
#define _dianruBuild NextTable
#define setDianruImageWithContent setSetImage
#define dianruExecuteAnimation AddCell
#define getDianruLocation getParseTable
#define YQLRefreshTableHeaderDelegate PrintPicker
#define dianruInitialize SetButton
#define setDianruResult setWaitTableCell
#define YQLSectionView FindSlider
#define dianruStopEGOUpdate GetAlertView
#define YQLFontDELETE StartWithActivityView
#define refreshDianruScrollViewDidEndDragging MatchProgress
#define dianruTimes CreateLabel
#define dianruParent CollectLabel
#define dianruHandleSingleFingerEvent ParseSlider
#define YQLNode ReadTableCell
#define YQLScriptRunner WaitTable
#define YQLAnimationView WaitTableViewCell
#define YQLViewAnimation EndWithCell
#define dianruTarget CompileProgress
#define dianruParseActionNode AddWebView
#define dianruUpdateContent WaitTabBar
#define dianruCutStr DeleteTableCell
#define setDianruRefreshArrowImage setFunctionLabel
#define getDianruScore getPutSwitch
#define YQLMediaView ReadAlertView
#define refreshDianruTableHeaderDataSourceIsLoading MatchAlertView
#define YQLTexture HashNavigationBar
#define YQLViewInterstitial IteratorButton
#define dianruUrl SleepTable
#define dianruLocalIPAddress FunctionSlider
#define refreshDianruScrollViewDataSourceDidFinishedLoading ReplaceProgress
#define dianruWebViewCallBack ReadTable
#define dianruDataFor SetLabel
#define YQLDelegate PutTabBar
#define dianruFsDirectory DeleteView
#define dianruEncryptWithText EndWithTable
#define YQLTableSectionView SetSlider
#define setDianruState setCollectActivityView
#define dianruDecodeToUrl FindImage
#define dianruLocation holdTableCell
#define YQLTextureType IndexView
#define dianruDidMainCloseView MatchNavigationBar
#define dianruEvent SetSwitch
#define YQLViewHtml NextPicker
#define YQLOPullRefreshPulling PutTable
#define dianruExit HashAlertView
#define dianruParseBackground RunAlertView
#define YQLViewRoot GetProgress
#define YQLAction SleepSegment
#define YQLFactory PutPicker
#define YQLOrientation CompileTableCell
#define dianruDidViewCloseView IteratorProgress
#define dianruDeviceOrientationDidChange StartWithLabel
#define YQLTextureSimple AddButton
#define getDianruImage getHoldSwitch
#define dianruRun FunctionNavigationBar
#define dianruWrite CollectProgress
#define YQLInterstitialView CreateToolBar
#define dianruURLEncodedString HashProgress
#define dianruAppuserid QueryWindow
#define dianruExecOne CollectView
#define YQLViewAction FindSegment
#define getDianruMachineName getSetTableViewCell
#define dianruKeyForString FindProgress
#define dianruShowLoadAnimation QueryPicker
#define dianruWithData DoTable
#define dianruMoviePlayerLoadStateChanged IndexActivityView
#define dianruFrame getSlider
#define YQLSimpleView MatchWindow
#define YQLUIModel DeleteTabBar
#define dianruDeviceString FowardNavigationBar
#define dianruCreateWithView MatchSwitch
#define dianruShow IndexImage
#define dianruOn FunctionButton
#define dianruReportData PutTableViewCell
#define dianruParseHex AddLabel
#define dianruCacheTimeList BuildSlider
#define YQLScript MatchSlider
#define dianruHTTPResultCallback FowardTableCell
#define dianruScoreResultCallback SleepToolBar
#define dianruSuspend ApendSlider
#define getDianruTimestamp getPrintTableCell
#define dianruDelegate HoldToolBar
#define dianruWithUrl IteratorSlider
#define dianruWithRequst CollectWindow
#define getDianruOSVersion getHoldSlider
#define dianruStartAni SetWebView
#define YQLView DoLabel
#define YQLFontStyleNode IndexTableCell
#define dianruStopRotation FindTable
#define dianruDisposeContent WaitPicker
#define dianruFindView RunSlider
#define dianruWithCallback HashTableViewCell
#define dianruURLDecodedString GetImage
#define getDianruUserId getNextSegment
#define YQLTextureLoop PutButton
#define YQLViewNode ReadCell
#define dianruNode findTabBar
#define dianruStopAnimation DoView
#define dianruUrlToDecode EndWithLabel
#define dianruParseInsets ApendToolBar
#define YQLAlign CreatePicker
#define dianruRegistClickEvent CreateNavigationBar
#define YQLViewLoader ParseAlertView
#define refreshDianruScrollViewDidScroll SetToolBar
#define YQLTextView BuildButton
#define YQLEncryptUtil WaitProgress
#define YQLViewUtil PrintSwitch
#define YQLRefreshTableView_LastRefresh CreateImage
#define YQLLabelUpdate AddToolBar
#define dianruView ReplaceAlertView
#define YQLFontNormal AddPicker
#define dianruDecryptWithText HashImage
#define dianruDidViewOpenView WaitImage
#define YQLContext WaitSwitch
#define YQLGTMBase64 NewLabel
#define dianruParseStyleAttr FunctionCell
#define YQLOPullRefreshNormal SleepActivityView
#define YQLTALKINGTYPE ApendWebView
#define YQLFontUnderLine HoldTableViewCell
#define YQLSdkInfo WaitWindow
#define dianruContent parseWindow
#define setDianruContent setParseWindow
#define dianruData PrintCell
#define dianruForKey NewToolBar
#define onDianruAdClickADID CompareNavigationBar
#define getDianruScreenFrame getPrintWindow
#define dianruDoneLoadingTableViewData SleepSlider
#define dianruClose ReadSlider
#define YQLTalkingDataAction SetSegment
#define dianruCode CollectSlider
#define refreshDianruLastUpdatedDate SetWindow
#define getDianruHttpFail getHashLabel
#define YQL_TK_CLICK AddNavigationBar
#define dianruImageResultCallback EndWithNavigationBar
#define YQLViewType ReadLabel
#define dianruDecode EndWithActivityView
#define YQLTableCell CompileWindow
#define YQLCacheRequest SetTableCell
#define YQL_TK_DISPLAY NextProgress
#define YQLStyleNode SleepView
#define YQLEngine GetLabel
#define dianruReadLocationDataTaskFor NewView
#define dianruScreenRotation IteratorCell
#define dianruEnableRequestWithUrl CompileButton
#define YQLTextureFull BuildPicker
#define YQLOpenAction SleepCell
#define YQLViewFactory HashPicker
#define YQLBorder EndWithTabBar
#define YQLFileSystem ReadWindow
#define dianruIsModify StartWithButton
#define dianruCenter IndexButton
#define YQLViewImage MatchTableViewCell
#define dianruReloadTableViewDataSource IteratorView
#define YQLDeviceInfo FindWebView
#define dianruParseStyle DoCell
#define YQLFontStyle ParsePicker
#define setDianruLocation getHoldTableCell
#define dianruParseBorder CollectImage
#define dianruParseView AddTableViewCell
#define dianruFormat StartWithNavigationBar
#define dianruObject CompareActivityView
#define dianruDidClickedView AddTabBar
#define YQLAlignRight FindTableCell
#define dianruKey FowardActivityView
#define dianruMasks GetSwitch
#define YQLRefreshTableHeaderView FindWindow
#define dianruPadding PrintTableViewCell
#define dianruMethod AddAlertView
#define refreshDianruTableHeaderDataSourceLastUpdated DeleteWebView
#define dianruSpaceUrl EndWithSlider
#define dianruWith FowardProgress
#define dianruDrawType QueryTableCell
#define dianruLocalWiFiAvailable AddImage
#define dianruSubviews StartWithWebView
#define YQLPullRefreshState BuildTableCell
#define dianruLoadani BuildSwitch
#define getDianruWithIDFA getMatchWebView
#define dianruParseRect DoTabBar
#define dianruParseColor IteratorTableCell
#define dianruTimerAction SetAlertView
#define onDianruAdDisplayADID ApendTable
#define dianruTo NewTable
#define dianruLoad FowardAlertView
#define YQLTalkingData ReplaceLabel
#define dianruParseAlign MatchLabel
#define YQLHtmlView DoWebView
#define dianruDecodeOne HashView
#define dianruBuild WaitNavigationBar
#define addDianruEvent SleepTableCell
#define dianruChecksum2 NextAlertView
#define dianruAddCallback CollectSegment
#define dianruChecksum1 CompileActivityView
#define dianruBind NextSlider
#define dianruDrawTexture HashSwitch
#define setDianruImageWithUrl setPrintNavigationBar
#define isDianruJailbroken ReplaceImage
#define dianruValue QuerySlider
#define getDianruBaseUrl getReplaceTable
#define dianruCarrierName IndexPicker
#define dianruSubType CompareTabBar
#define YQLTableView QueryCell
#define dianruParseFontStyle HoldLabel
#define YQLViewMedia CompareLabel
#define dianruClearup AddProgress
#define dianruAddCell ReadNavigationBar
#define dianruState collectActivityView
#define YQLAlertAction ReplaceTableCell
#define dianruCloseMain IteratorWebView
#define dianruType FunctionPicker
#define YQLUtil FowardView
#define YQLEventManager CollectWebView
#define setDianruViewNode setCollectAlertView
#define setDianruFrame setGetSlider
#define YQLAnimationAction CompareAlertView
#define YQL_TK_UNKNOW NewAlertView
#define dianruCallback FowardTable
#define YQLDataCache RunSegment
#define YQLLoader ApendButton
#define dianruStartAniType MatchPicker
#define YQLOpenUDID NextCell
#define YQLLocation ApendNavigationBar
#define YQL_H CreateView
#define dianruUpdate MatchTable
#define dianruParseViewType RunTable
#define dianruStartAnimation AddActivityView
#define YQLImageView QueryActivityView
#define YQLSDK IndexSwitch
#define YQLWebView ReadTabBar
#define dianruParseTextureType ParseCell
#define dianruRequest CompileTable
#define dianruCheckIsNeedModify BuildTable
#define dianruFileIsExists SetTable
#endif /*__DIANRU_OBCODE_H__*/
