#ifndef MIIDIBAS_PUBAPI_H
#define MIIDIBAS_PUBAPI_H
//confuse string at Wed Jan  7 17:53:05 CST 2015
#define MiidiManager XHtptbkrLwKhOHWN
#define setMiidiBasAppPublisher sfoKAXBCHGbRGnMW
#define withMiidiBasAppSecret SfSFNGuBeEdIvSFy
#define setMiidiBasMarketChannelID cYgsThQYxSRMdxLz
#define getMiidiBasSdkVersion HJYBnJovhWmUPgng
#define MiidiAdSpot wTdOCOhxGuNdFsRE
#define requestMiidiBasSpotAd zjTTEgOGoDEzkyqf
#define isMiidiBasSpotAdReady EMwgbYGIDutfubvu
#define displayMiidiBasSpotAdWithBlock AaOnDGbVzhvTvkJp
#define withMiidiBasBlock nXadRcEOppgqwaVP
#define withMiidiBasTime bEuPHPGaFrTWuOou
#define MiidiAdView BtxymTZwriiVJDin
#define createMiidiBasAdViewWithSizeIdentifier kYBNCxANztyCwOYk
#define withMiidiBasDelegate QBOUaSTShikNbCtq
#define initMiidiBasAdViewWithContentSizeIdentifier uOaTVxQXZiQuQDSi
#define requestMiidiBasAd BNwFOimDzFpnwVbz
#define MiidiAdViewDelegate WfmAxstlRmEwugkh
#define didMiidiBasReceiveAd qyHBmPKkpGoVXzEB
#define didMiidiBasFailReceiveAd lpdeTxoNlmYJOXBR
#define withMiidiBasError WuIEtVnGdPDFbrjV
#define didMiidiBasShowAdWindow nAdbEhlWtdzNNkmP
#define didMiidiBasDismissAdWindow beYGBKRxADSYhXXc
#endif
