#ifndef __DIANRU_OBCODE_H__
#define __DIANRU_OBCODE_H__
#define getDianruDeviceOrientation getReadForest
#define setDianruRequestLaseTimeWithUrl setLockTableViewCell
#define dianruViewload ParseEgg
#define dianruStartEGOUpdate SetRice
#define dianruSpendScoreResultCallback CollectWebView
#define getDianruMainBounds getServeForest
#define dianruObjectForKey CloneWhale
#define dianruDidJumpedView LookBread
#define YQL_V MatchFeature
#define dianruFindview DoCache
#define getDianruAppId getCompilePotato
#define YQLHttpActionExecer KillPiano
#define YQLTextField LookActivityView
#define dianruWithMySelf CoverParrot
#define YQLAlignCenter StartWithTableCell
#define dianruNewCheckSum MatchRice
#define YQLANIMATION_TYPE RunAchieve
#define dianruQueryString AnswerBelieve
#define dianruResizeToFit DoProgress
#define YQLMacros StudyNoodles
#define dianruReadLocationFor FindMemory
#define dianruEnable BiteAchieve
#define dianruRequestBlock CostChicken
#define dianruImageFor CrashTabBar
#define YQLTextureInfo NeedTableCell
#define dianruTimeout InviteView
#define dianruExpire AnswerButton
#define YQLViewUnknow MaintainMemory
#define dianruParseEvent DevelopDolphin
#define dianruParseFloat FallView
#define dianruDidReportedView IteratorLabel
#define YQLTextureVertical RunPicker
#define YQLReqestResultType CrashRice
#define YQLViewCell NextChicken
#define getDianruSpendScore getFindBear
#define YQLTextureHorizontal MatchLabel
#define dianruShareIstance CostView
#define dianruActions LookFlower
#define dianruBuildWithName DecorateActivityView
#define YQLRunningProcess CallCake
#define YQLSetAction MaintainDamage
#define YQLCodeAction NeedCountry
#define setDianruNode setFindNavigationBar
#define dianruDuration CoverCache
#define YQLNotificationAction QueryRadish
#define dianruExec HashBear
#define dianruApplicationKey FunctionWebView
#define dianruLoadView ServeNoodles
#define addDianruStyle ReplaceView
#define dianruRequestSpace DevelopLaugh
#define dianruCreate MatchTomato
#define dianruContext GetMemory
#define dianruCancel ShowSnake
#define YQLAlignLeft PutMemory
#define YQLViewText CreateNoodles
#define initWithDianruContext initGeneralDolphin
#define dianruName LookSlider
#define dianruParseTextAttr QuerySpider
#define getDianruMacAddress getInviteTable
#define setDianruArrowData setWaitRadish
#define YQLHttpRequest NeedForest
#define dianruSubview StartWithMemory
#define setDianruDelegateNull setCostWhale
#define getDianruWifiIP getBuildSegment
#define dianruReadNetDataTaskFor DoPicker
#define dianruStopLoadAnimation CollectAdvice
#define YQLViewTextField LockTable
#define dianruFsPath DanceCache
#define dianruRunningProcesses HashActivityView
#define dianruEnableUseRadius FallSpider
#define dianruDidDataReceivedView DeleteDolphin
#define YQLBeginAction BuildPumpkin
#define YQLActionNode RunTomato
#define dianruWakeup ShowExperience
#define YQLFontBold NeedCarrot
#define YQLViewSection BrushFlower
#define YQLUrlCache IteratorWindow
#define dianruEngine CallTabBar
#define dianruMovieFinishedCallback CatchNoise
#define YQLViewSimple PutSubject
#define dianruLoadData BiteFeature
#define dianruHide AnswerAlertView
#define dianruRemove CutPlant
#define dianruResult maintainSnake
#define YQLFontStyle_ALL CallTableCell
#define YQLViewDelegate SleepButton
#define refreshDianruTableHeaderDidTriggerRefresh IndexWeed
#define dianruJump BeatInterest
#define dianruRect ApendBelieve
#define dianruAutoresize CutToolBar
#define dianruStartRotation PrintCache
#define YQLViewTable AnswerSwitch
#define addDianruChild CallDessert
#define dianruPurge WaitWebView
#define getDianruFreeSpace getProductCake
#define YQLOPullRefreshLoading CollectOnion
#define YQLHttpAction MaintainPlant
#define dianruText PrintBear
#define dianruImage DecorateNoise
#define _dianruBuild BrushRadish
#define setDianruImageWithContent setReplaceForest
#define dianruInitialize InviteToolBar
#define YQLRefreshTableHeaderDelegate CompareRice
#define dianruExecuteAnimation CrashOnion
#define getDianruLocation getCreateDolphin
#define dianruMD5Hash CloneFlower
#define setDianruResult setMaintainSnake
#define YQLSectionView StartWithWhale
#define dianruStopEGOUpdate CostWeed
#define YQLFontDELETE ProductBear
#define refreshDianruScrollViewDidEndDragging AnswerForest
#define dianruTimes AnswerActivityView
#define dianruParent IteratorSlider
#define dianruHandleSingleFingerEvent NextCell
#define YQLNode FowardBear
#define YQLScriptRunner DeleteMemory
#define YQLAnimationView CatchView
#define YQLViewAnimation BitePotato
#define dianruTarget BuildMemory
#define getDianruQueryString getStartWithDamage
#define getDianruReportUrl getCreateKilometer
#define dianruParseActionNode CallSlider
#define dianruUpdateContent PermitAchieve
#define dianruCutStr HashMemory
#define dianruCheckSum BitePlant
#define getDianruWifiInfo getMatchSnake
#define setDianruRefreshArrowImage setCoverSlider
#define getDianruScore getAddTable
#define YQLMediaView HoldSegment
#define refreshDianruTableHeaderDataSourceIsLoading StartWithLaugh
#define YQLTexture MaintainTableViewCell
#define YQLViewInterstitial ShowView
#define dianruUrl PutRadish
#define dianruLocalIPAddress PrintTree
#define refreshDianruScrollViewDataSourceDidFinishedLoading CallImage
#define dianruAnis DecorateBread
#define dianruWebViewCallBack AddSegment
#define dianruDataFor BlowFeature
#define YQLDelegate AnswerSpider
#define dianruFsDirectory BeatCarrot
#define dianruEncryptWithText BitePiano
#define setDianruState setReplaceTree
#define dianruDecodeToUrl FindCarrot
#define dianruLocation lockKilometer
#define YQLTextureType ServeLabel
#define dianruDidMainCloseView StartWithFlower
#define getDianruFingerprint getStudyImage
#define dianruEvent BeatDessert
#define YQLViewHtml AddParrot
#define YQLOPullRefreshPulling FowardSegment
#define dianruExit MakeOnion
#define dianruParseBackground ParseWeed
#define YQLViewRoot FowardDolphin
#define YQLAction HoldPotato
#define YQLFactory StartWithTree
#define YQLDeleteAction BrushBread
#define YQLOrientation ShowCell
#define dianruDiskInfo HashAlertView
#define dianruDidViewCloseView CreateBread
#define dianruDeviceOrientationDidChange CompileCell
#define YQLTextureSimple GetSlider
#define getDianruImage getMakeSegment
#define dianruRun FunctionFlower
#define dianruWrite SetTabBar
#define YQLInterstitialView AddWindow
#define dianruURLEncodedString BiteRice
#define dianruAppuserid IndexBelieve
#define dianruExecOne CutRadish
#define YQLViewAction WaitNoise
#define getDianruMachineName getPrintSwitch
#define dianruShowLoadAnimation CompileSpider
#define dianruKeyForString AnswerTableCell
#define dianruWithData LoadEgg
#define dianruMoviePlayerLoadStateChanged ServeImage
#define dianruFrame danceForest
#define YQLSimpleView PermitSpider
#define YQLUIModel LookImage
#define dianruDeviceString MaintainTable
#define dianruCreateWithView PutAdvice
#define dianruShow BrushFeature
#define dianruOn CompilePumpkin
#define dianruReportData GetImage
#define YQLIfAction GetSegment
#define dianruParseHex GetAchieve
#define dianruCacheTimeList AddLaugh
#define YQLScript RunWeed
#define dianruHTTPResultCallback CallSwitch
#define dianruScoreResultCallback DecorateFlower
#define dianruKeychainIdfa MakeChicken
#define getDianruTimestamp getFowardTrumpet
#define dianruSuspend PermitNavigationBar
#define dianruDelegate SleepCountry
#define dianruWithRequst ApendPotato
#define dianruWithUrl ApendCache
#define dianruHash CoverRadish
#define getDianruOSVersion getLoadCache
#define dianruStartAni BlowEgg
#define YQLView GetFlower
#define YQLFontStyleNode ApendForest
#define dianruStopRotation CoverCell
#define dianruDisposeContent KillProgress
#define dianruWithCallback ProductProgress
#define dianruFindView ParseForest
#define dianruURLDecodedString SleepTomato
#define YQLViewNode IteratorLaugh
#define YQLTextureLoop CompileForest
#define getDianruUserId getLookButton
#define dianruNode findNavigationBar
#define dianruStopAnimation NeedDamage
#define dianruUrlToDecode CompileCountry
#define dianruParseInsets MaintainSwitch
#define dianruKeychainMac GeneralBelieve
#define YQLAlign CutCake
#define dianruRegistClickEvent PermitEgg
#define YQLViewLoader ProductWebView
#define refreshDianruScrollViewDidScroll ShowWeed
#define YQLTextView PrintCell
#define YQLEncryptUtil StudyWebView
#define YQLViewUtil RunPiano
#define YQLRefreshTableView_LastRefresh RunBear
#define dianruString2Hex NextToolBar
#define YQLLabelUpdate IndexRadish
#define dianruView AddSwitch
#define YQLCheckSum CatchAchieve
#define YQLFontNormal ChangeBroccoli
#define dianruDecryptWithText DanceInterest
#define dianruDidViewOpenView CollectTree
#define YQLContext CrashCache
#define dianruSysctlbynameFctn AddProgress
#define YQLGTMBase64 BiteTree
#define dianruParseStyleAttr IteratorPiano
#define YQLOPullRefreshNormal ChangeToolBar
#define YQLKey AnswerView
#define YQLTALKINGTYPE GeneralVoice
#define YQLFontUnderLine WaitCache
#define YQLSdkInfo ProductRadish
#define dianruContent developPicker
#define setDianruContent setDevelopPicker
#define dianruData FindForest
#define dianruForKey CrashView
#define onDianruAdClickADID DeleteWhale
#define getDianruScreenFrame getKillNavigationBar
#define dianruLayer CompareVoice
#define dianruClose ReadBear
#define YQLTalkingDataAction NextTableCell
#define dianruCode DevelopTableCell
#define refreshDianruLastUpdatedDate CollectLabel
#define getDianruHttpFail getGetAdvice
#define YQL_TK_CLICK CostNoodles
#define dianruImageResultCallback ChangeNoodles
#define YQLViewType FunctionOnion
#define YQLTableCell BeatEgg
#define YQLCacheRequest DoOnion
#define dianruDecode MatchTableViewCell
#define getDianruDiskid getReplaceSwitch
#define YQL_TK_DISPLAY CostRadish
#define YQLStyleNode DanceCountry
#define YQLEngine LockEgg
#define dianruScreenRotation LockTomato
#define getDianruKey getSetTable
#define dianruEnableRequestWithUrl EndWithCarrot
#define YQLTextureFull CollectBelieve
#define YQLOpenAction CatchAlertView
#define YQLViewFactory DeleteSwitch
#define YQLBorder SleepNoise
#define YQLFileSystem DeletePumpkin
#define dianruIsModify InviteSegment
#define dianruCenter SetFlower
#define YQLViewImage HoldSlider
#define YQLDeviceInfo ReadTrumpet
#define dianruParseStyle AddInterest
#define YQLFontStyle BlowParrot
#define setDianruLocation getLockKilometer
#define dianruParseBorder QueryAlertView
#define dianruParseView MakeLiberty
#define dianruFormat LookView
#define dianruObject PrintPicker
#define dianruDidClickedView ShowEgg
#define YQLAlignRight CollectSnake
#define dianruKey BeatSpider
#define dianruMasks ChangeSegment
#define YQLRefreshTableHeaderView CloneImage
#define dianruPadding ParseExperience
#define dianruMethod CoverRice
#define refreshDianruTableHeaderDataSourceLastUpdated PutProgress
#define dianruSpaceUrl BeatNoise
#define dianruWith IteratorProgress
#define dianruDrawType MakeDolphin
#define dianruLocalWiFiAvailable DanceDamage
#define dianruSubviews FunctionTabBar
#define YQLPullRefreshState ComparePotato
#define dianruLoadani LoadRice
#define getDianruWithIDFA getBlowSpider
#define dianruParseRect FindTabBar
#define dianruParseColor EndWithNoodles
#define dianruTimerAction DevelopLabel
#define YQLEndAction LookLaugh
#define onDianruAdDisplayADID DoKilometer
#define dianruTo ReplaceTrumpet
#define dianruLoad MakeToolBar
#define getDianruWifiSSID getBuildInterest
#define YQLTextFieldBri BrushCarrot
#define YQLTalkingData CostAlertView
#define dianruParseAlign ShowTomato
#define YQLHtmlView FindPiano
#define dianruDecodeOne ApendVoice
#define dianruBuild QueryAdvice
#define addDianruEvent DoVoice
#define dianruChecksum3 RunFeature
#define dianruAddCallback IteratorTableCell
#define dianruChecksum2 CloneProgress
#define dianruChecksum1 SleepDessert
#define dianruBind FunctionWindow
#define dianruDrawTexture CrashDamage
#define setDianruImageWithUrl setCloneAdvice
#define isDianruJailbroken GetSwitch
#define getDianruBaseUrl getGetTableCell
#define dianruValue EndWithTableViewCell
#define dianruCarrierName CollectExperience
#define dianruSubType IteratorNoise
#define YQLTableView BuildWhale
#define dianruParseFontStyle AddRice
#define YQLViewMedia BuildPiano
#define dianruClearup CatchAdvice
#define dianruState replaceTree
#define YQLAlertAction StartWithAchieve
#define dianruCloseMain CloneSpider
#define dianruType LockView
#define dianruParseConf MakeFlower
#define YQLUtil CallEgg
#define YQLEventManager LockPicker
#define setDianruViewNode setPermitAlertView
#define setDianruFrame setDanceForest
#define YQLAnimationAction AddPumpkin
#define YQL_TK_UNKNOW ReadButton
#define dianruCallback LockSubject
#define YQLDataCache CompileCarrot
#define YQLLoader BlowTableViewCell
#define dianruStartAniType AnswerBroccoli
#define YQLOpenUDID MakeActivityView
#define YQLLocation CollectSlider
#define YQL_H FallEgg
#define dianruUpdate CloneParrot
#define dianruParseViewType CatchTree
#define dianruStartAnimation BorrowToolBar
#define YQLImageView CompareCarrot
#define YQLSDK ShowTableViewCell
#define YQLWebView CutSegment
#define dianruParseTextureType ParseAdvice
#define dianruRequest IteratorChicken
#define dianruExecIfElse WaitRice
#define dianruCheckIsNeedModify CallPotato
#define getDianruDiskTotalSpaceEx getDevelopSwitch
#define dianruFileIsExists CoverCountry
#endif /*__DIANRU_OBCODE_H__*/
